"""Minimal .env read/update helper — stdlib only, no python-dotenv dependency."""

import re
from pathlib import Path

_LINE_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$")


def read_env(path: Path) -> dict:
    if not path.exists():
        return {}
    values = {}
    for line in path.read_text().splitlines():
        match = _LINE_RE.match(line.strip())
        if match:
            values[match.group(1)] = match.group(2)
    return values


def ensure_keys(path: Path, defaults: dict) -> dict:
    """Read path, add any missing keys from `defaults`, write back, return
    the full merged dict. Existing values and comments are left untouched;
    new keys are appended under a marker comment."""
    existing_lines = path.read_text().splitlines() if path.exists() else []
    existing = read_env(path)
    missing = {k: v for k, v in defaults.items() if k not in existing}

    if missing:
        if existing_lines and existing_lines[-1].strip():
            existing_lines.append("")
        existing_lines.append("# Auto-generated by scripts/configure_instances.py")
        for key, value in missing.items():
            existing_lines.append(f"{key}={value}")
        path.write_text("\n".join(existing_lines) + "\n")

    existing.update(missing)
    return existing
